name: phi.ag - Run Playwright
description: Run Playwright container action
author: phi.ag
inputs:
  version:
    description: Playwright version
    default: v1.48.1-noble@sha256:0b464b63fb1c6ceae1a47c8d615c016de277fd08a1df773394f9bba77f4a7550
  run:
    description: Commands to execute
    required: true
    type: string
  options:
    description: Additional docker arguments
    required: false
branding:
  icon: play
  color: orange
runs:
  using: composite
  steps:
    - name: Run Playwright
      shell: bash
      run: |
        set -euo pipefail

        mkdir -p .run-playwright
        echo "#!/usr/bin/env bash" > .run-playwright/run.sh
        echo "set -euo pipefail" >> .run-playwright/run.sh
        echo '${{ inputs.run }}' >> .run-playwright/run.sh
        chmod +x .run-playwright/run.sh

        ENV="$(echo '${{ toJson(env) }}' | jq -r 'keys | map("-e \(.)") | join(" ")')"

        set -x
        docker run --rm \
          --workdir /github/workspace \
          -v "${{ github.workspace }}":/github/workspace \
          -e CI=true -e HOME=/root ${ENV} \
          ${{ inputs.options }} \
          mcr.microsoft.com/playwright:${{ inputs.version }} \
          .run-playwright/run.sh
